# quiz-builder/docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz-postgres
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpassword
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network

volumes:
  postgres_data:

networks:
  quiz-network:
    driver: bridge